production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  # encoding: utf8mb4

development:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
#  adapter: sqlite3
#  database: db/redmine.sqlite3